apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    {{ range $key, $val := (merge .Values.global.ingress.annotations .Values.ingress.annotations) }}
    "{{ $key }}": |
      {{- $val | nindent 6 }}
    {{ end }}
    {{ if .Values.global.isProd }}
    {{- include "annotations.letsencrypt-cert" . | nindent 4 }}
    {{- end }}
  labels:
    component: {{ or .Values.component .Chart.Name }}
    application: {{ .Values.global.repositoryName }}
  name: {{ or .Values.component .Chart.Name }}
  namespace: {{ .Values.global.namespace }}
spec:
  rules:
    - host: >-
        {{- include "defaults.ingress-host" . | nindent 8 }}
      http:
        paths:
          - backend:
              service:
                name: {{ or .Values.component .Chart.Name }}
                port:
                  name: http
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - >-
          {{- include "defaults.ingress-host" . | nindent 10 }}
      {{- if .Values.global.isProd }}
      secretName: {{ or .Values.certSecretName (print (or .Values.component .Chart.Name) "-crt") }}
      {{- else }}
      secretName: "wildcard-crt"
      {{- end }}
