{{ if .Values.autoscale.enabled }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ or .Values.component .Chart.Name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    component: {{ or .Values.component .Chart.Name }}
spec:
  minReplicas: {{ .Values.autoscale.minReplicas }}
  maxReplicas: {{ .Values.autoscale.maxReplicas }}
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: {{ .Values.autoscale.averageUtilization.cpu }}
          type: Utilization
      type: Resource
    - resource:
        name: memory
        target:
          averageUtilization: {{ .Values.autoscale.averageUtilization.memory }}
          type: Utilization
      type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ or .Values.component .Chart.Name }}
{{ end }}