on:
  workflow_call:
    inputs:
      webhookUri:
        required: false
        type: string
      triggerWebhook:
        required: false
        type: boolean
      environment:
        required: false
        type: string
    secrets:
      KUBEWEBHOOK_TOKEN:
        required: true

jobs:
  webhook:
    name: Kontinuous Pipeline (via webhook)
    runs-on: ubuntu-latest
    steps:

      - name: Starting Deployment ðŸŽ¬
        uses: SocialGouv/kontinuous/gh-actions/deployment-starting@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Kontinuous Pipeline ðŸ¥·
        uses: SocialGouv/kontinuous/gh-actions/deploy-via-webhook@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          webhookToken: ${{ secrets.KUBEWEBHOOK_TOKEN }}
          webhookUri: ${{ inputs.webhookUri }}
          triggerWebhook: ${{ inputs.triggerWebhook }}
          environment: ${{ inputs.environment }}
      
      - name: Reporting ðŸ“œ
        uses: SocialGouv/kontinuous/gh-actions/deployment-reporting@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}