on:
  workflow_call:
    inputs:
      webhookUri:
        required: false
        type: string
    secrets:
      KUBEWEBHOOK_TOKEN:
        required: true

jobs:
  production:
    name: Kontinuous Production Pipeline ðŸš€
    runs-on: ubuntu-latest
    environment: production
    steps:
      
      - name: Starting Deployment ðŸŽ¬
        uses: SocialGouv/kontinuous/gh-actions/deployment-starting@v1
        id: deployment-starting
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Kontinuous Pipeline ðŸ¥·
        uses: SocialGouv/kontinuous/gh-actions/deploy-via-webhook@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          webhookToken: ${{ secrets.KUBEWEBHOOK_TOKEN }}
          webhookUri: ${{ inputs.webhookUri }}
          triggerWebhook: "true"
          environment: "prod"
      
      - name: Reporting ðŸ“œ
        uses: SocialGouv/kontinuous/gh-actions/deployment-reporting@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          deployment_id: ${{ steps.deployment-starting.outputs.deployment_id }}